### PR TITLE
Refactoring of the code.

### PR DESCRIPTION
**Pull request by ignabelitzky**
I made a simple refactoring of the code in various files for readability, also made some functions for random generation of ints and floats. I added a base .gitginore to the project, and format all the source files (.hpp and .cpp files) with the Microsoft standard of code for C plus plus projects.

Hope you can approve this Pull Request and please consider to follow me on GitHub... cheers!

### CODE REVIEW

**Comment by Martin-Reparaz** [comment]
Hi ignabelitzky,

Thank you for submitting your pull request and for your contribution to the project. I really appreciate your interest in improving the code readability.

However, after reviewing your pull request, I've encountered a compilation issue due to multiple definitions in the `utils.cpp` and `main.cpp` files. It seems that some variables are being defined in both files, causing conflicts during compilation.

Compilation_issue

To address this issue, I suggest reviewing the variables and functions in the `utils.cpp` and `main.cpp` files to ensure there are no multiple definitions. If possible, I would recommend using local variables or functions instead of global variables to avoid these conflicts.

If you need further assistance in resolving this issue, feel free to ask. I'm here to help in any way I can.

Thanks again for your contribution and for your patience as we work together to resolve this issue.

Best regards,
Martin J. Reparaz

**Comment by ignabelitzky** [comment]
> Hi ignabelitzky,
> 
> Thank you for submitting your pull request and for your contribution to the project. I really appreciate your interest in improving the code readability.
> 
> However, after reviewing your pull request, I've encountered a compilation issue due to multiple definitions in the `utils.cpp` and `main.cpp` files. It seems that some variables are being defined in both files, causing conflicts during compilation.
> ...

Check it now; it should be fixed. I also changed the definition of the read_params(...) function to work as expected.
Cheers!

**Comment by Martin-Reparaz** [comment]
Hi ignabelitzky,

Thank you for your quick response and for making those changes. However, after testing it on both my PC and in an Nvidia Jetson board, the simulator still isn't functioning properly. On both systems, the window do pop up, but it remains black. I also tried to modify the parameters for any change, but still same result. Could you please recheck the changes or consider any other factors that might be affecting the simulator's performance?

Thanks again for your contribution.

**Comment by ignabelitzky** [comment]
I'll check the code as soon as I can. This week has been very busy for me.
While executing the code, I noticed that sometimes the particles appear and sometimes they don't, and I attributed this to the initial value of the particles.
I'll leave you what I mean with that here:
simulation_GIF

**Comment by ignabelitzky** [comment]
The bug was in my implementation of calculate_gravity_force(...) function...
Please check it out, and confirm that it works.
@Martin-Reparaz

**Comment by Martin-Reparaz** [comment]
Hello Ignabelitzky,

Yes, it's working now. However, there seems to be an error in the calculation of particle velocities after the collision. I'll try to correct it myself. Thank you again for your collaboration.

**Pull request merged**
